### ISSUE TITLE
Add logging to track down connection/stream issues

### ISSUE THREAD

**Issue by pke** [andywer/http-event-stream#12]
I can successfully establish an event stream on my dev machine localhost.
However on the production machine behind a `Caddy` with `transparent` proxy settings I see no events on the client. The socket seems to be connected though, according to Chrome network tab.

Is there a way to debug connection issues like that?
What could be the reason streaming does not work?

**Comment by andywer** [comment]
Ohh, right into the hornet's nest 😅

Well, the first thing I would try is really just connecting to the stream via `curl -v -H "Accept: text/event-stream" <url>` and see what happens.

You can already check two things this way, without any background noise:
- Do you receive any events?
- Does the connection remain open or does it close?

Debugging those kinds of proxy issues is a bit more pleasant than debugging the same issues with websockets, but not by much... Haven't tried proxying SSE streams with Caddy. You might need to set some option to keep the connection alive or you need to prevent buffering, so it sends the data immediately to the client.

You are right, though. There should be a decent debug logging in place, probably using the `debug` package. I will create a new issue for that.

**Comment by pke** [comment]
`debug` logging is preferred, yes. Thanks!

Chrome shows the stream to be open and not closed but no events are received.

Buffering could be a thing! Cause there is "gzip" enabled globally in Caddy for the server. I'm pretty sure it does not work on streams, how could it. 

But unfortunately I need to wait for the admin to fix that setting. But if we could get the logging in place I'll test it.

**Comment by pke** [comment]
I can hereby confirm the gzip directive was the culprit. So we should probably add a note about compression to the readme. How could we detect that no events leave the server and reach the client?

**Comment by andywer** [comment]
> So we should probably add a note about compression to the readme.

Sure thing! Would you mind opening a PR? Otherwise I can do it, too, later today.

> How could we detect that no events leave the server and reach the client?

You mean server-side? I think we can’t...

**Comment by andywer** [comment]
Btw, big thanks for helping to improve this little package 👍😊

**Comment by pke** [comment]
so when you are writing to a socket there is no way of detecting if there is someone listening on the other end?

One of the benefits of SSE is that its not bi-directional, so we can't use a ping mechanism to let the client pong back.

So maybe this issue needs to be completely handled by the client code, like that it expects the server to send at least a "hello" or "connected" event to the client. If that event does not reach the client, then there is something blocking the package leaving the server.

I'll close this issue now, since there is not much this package can do to detect connection issues.
