### ISSUE TITLE
Question about using this with http2

### ISSUE THREAD

**Issue by caleblawrence** [andywer/http-event-stream#5]
Hello, 
I had a quick question. You mention http2 a couple places on the README but in your example for Koa and Express you appear to be using http1.

Is that the case? To use http2 for Koa, as far as I know, you would have to do: 
```javascript
const fs = require('fs');
const http2 = require('http2');
const koa = require('koa');


const app = new koa();
// response
app.use(ctx => {
    ctx.body = 'Hello Koa';
});


const options = {
    key: fs.readFileSync(__dirname + '/server.key'),
    cert: fs.readFileSync(__dirname + '/server.crt')
}

const server = http2.createSecureServer(options, app.callback());
server.listen(3000);
```

So, I'm guessing this package will still work if I was to do this? Thanks so much for your help.

**Comment by andywer** [comment]
Hey @caleblawrence!

I wouldn't waste any breath on enabling HTTP/2 in my node backend. Just make sure your load balancer / reverse proxy (nginx, traefik, ...) offers HTTP/2 when talking to the client 😉

Read more here: https://serverfault.com/a/765337

**Comment by caleblawrence** [comment]
Oh ok I see. I'll look into that then. Thanks a lot @andywer!
